// GENERATED FILE — do not edit by hand.
// Run `npm run build:curated` to regenerate from src/data/activities.ts.
//
// Built: 2026-08-15T12:11:50.742Z
// 26 curated locals, median 266 chars, 0 truncated at 500.
//
// These are the island's own picks — beaches, fish fries, walking tours — that
// live in src/data/activities.ts and never reached `item_embeddings`, so
// semantic search could not return them. See tools/run-build-curated.cjs for
// why they are copied rather than imported.
export const CURATED_SEARCH_ENTRIES: Array<{ id: string; text: string }> = [
  { id: "eagle-beach-morning", text: "Eagle Beach Morning Session. Consistently voted one of the Caribbean's top beaches. Wide, powdery sand — uncrowded before 9am. Find a spot under a divi-divi tree. \"Skip the hotel beach. Eagle Beach before breakfast is one of those mornings you'll remember for years.\" — Rosario Located in Eagle Beach, Noord. Category: Beaches." },
  { id: "baby-beach-snorkel", text: "Baby Beach & Snorkel Lagoon. Aruba's best-kept secret on the southern tip. Shallow, calm lagoon — a natural nursery for tropical fish and ideal for beginning snorkelers. \"Drive past the refinery and keep going. Bath-warm and crystal clear.\" — Miguel Located in Seroe Colorado, San Nicolas. Category: Beaches." },
  { id: "arikok-hiking", text: "Arikok National Park Hike. 20% of the island. Limestone cliffs, natural pools, ancient cave paintings, and the dramatic northeast coast. Self-guided trails — no tour needed. \"Most tourists never leave Palm Beach. Arikok shows you what Aruba actually is.\" — Danilo Located in Arikok National Park. Category: Activities." },
  { id: "california-lighthouse-sunset", text: "California Lighthouse Sunset. Northernmost point of the island, perfect golden-hour cliffside views. Tonight's sunset is at 6:42pm — arrive 30 min early. \"This is the spot for any first-night couple.\" — Jana Located in Hudishibana, Noord. Category: Beaches." },
  { id: "flamingo-renaissance", text: "Flamingo Beach Day Pass. Private island with the famous wild flamingos. Day passes are limited and book out weeks ahead in peak season. \"Worth the early ferry — the flamingos are most active before 10am.\" — Lara Located in Renaissance Island. Category: Activities." },
  { id: "boca-catalina-snorkel", text: "Catamaran Sail & Snorkel at Boca Catalina. Catamaran drops anchor at Boca Catalina — shallow rocky cove with exceptional clarity. Sea turtles feed here regularly. \"Stay back and let the turtles come to you.\" — Carlos Located in Boca Catalina, Palm Beach. Category: Watersports." },
  { id: "antilla-wreck-dive", text: "Antilla Shipwreck Snorkel Cruise. 400-foot WWII German freighter — the Caribbean's largest sunken ship. Snorkel over the upper sections through coral-encrusted portals in 20–30 feet of crystal-clear water. \"You can see the whole wreck from the surface. Unreal.\" — Ramon Located in Off Malmok Beach. Category: Watersports." },
  { id: "zeerovers-fresh-catch", text: "Zeerovers Fish Fry. Aruba's most authentic food experience — local fisherman's cooperative, fried fish by the pound, cash only. \"Order the wahoo.\" — Wilhelmina Located in Savaneta. Category: Food." },
  { id: "gasparito-restaurant", text: "Dinner at Gasparito. 17th-century cunucu house in Noord. Traditional Aruban cuisine and the famed keshi yena. \"My family's special-occasion spot.\" — Sofia Located in Noord. Category: Food." },
  { id: "oranjestad-walking", text: "Oranjestad Walking Tour. Pastel Dutch-Colonial downtown — Fort Zoutman, the museum, fresh pan bati at the panaderia. \"Before 9am, the city belongs to us again.\" — Hendrik Located in Oranjestad. Category: Tours." },
  { id: "kitesurfing-lesson", text: "Kitesurfing at Fisherman's Huts. Constant 15–25 knot trade winds, shallow flat water. Aruba is one of the world's top kite spots. \"Consistent wind 320+ days a year.\" — Sven Located in Fisherman's Huts, Malmok. Category: Watersports." },
  { id: "natural-pool-jeep", text: "Natural Pool 4x4 & Snorkel Tour. Rugged 4x4 drive across Arikok's volcanic dunes to the lava-ringed Conchi natural pool — then snorkel in its sheltered cove. \"Not easy to get to. That's the whole point.\" — Marco Located in Arikok. Category: Tours." },
  { id: "malmok-beach", text: "Malmok Beach Snorkel. Calm, shallow water over a rocky bottom — Aruba's best shore-snorkel beach. Green turtles and reef fish right off the rocks, with the Antilla wreck just offshore. \"Get in before the catamarans arrive around 10 and the turtles are all yours.\" — Edsel Located in Malmok, Noord. Category: Beaches." },
  { id: "tres-trapi", text: "Tres Trapi Turtle Cove. \"Three steps\" — concrete stairs drop you into a sheltered cove where green turtles graze the seagrass. Free shore entry, no boat needed, just south of Boca Catalina. \"Walk down the steps slowly, float, and wait. They surface for air right beside you.\" — Glennis Located in Tres Trapi, Noord. Category: Beaches." },
  { id: "manchebo-beach", text: "Manchebo Beach Sunset. Aruba's widest stretch of sand, far quieter than neighbouring Eagle. Acres of space, a handful of thatched palapas, and one of the island's best unobstructed sunsets. \"Eagle gets the crowds — walk five minutes south to Manchebo and it's just you and the sunset.\" — Yarzagaray Located in Manchebo, Eagle Beach. Category: Beaches." },
  { id: "divi-beach", text: "Druif (Divi) Beach. Soft white sand along the low-rise strip — calm, gently shelving water that suits families, and an easy barefoot stroll up to Eagle Beach. \"Druif is where locals bring the kids on a Sunday. Calm, shallow, no fuss.\" — Ruthlyn Located in Druif, Oranjestad. Category: Beaches." },
  { id: "mangel-halto", text: "Mangel Halto Lagoon. A mangrove-fringed lagoon on the calm south coast. Wade in from the dock or kayak the channels; just past the mangroves the reef drops into a wall of fish. \"Snorkel out through the cut in the reef — but only on a calm day, and always head back before the current turns.\" — Orlando Located in Pos Chiquito, Savaneta. Category: Beaches." },
  { id: "rodgers-beach", text: "Rodger's Beach. A calm crescent right next to Baby Beach, framed by the old refinery hills. Glassy water, a local snack truck, and a fraction of the crowds. \"Everyone piles into Baby Beach. Rodger's, right next door, is where San Nicolas actually swims.\" — Ditmar Located in Seroe Colorado, San Nicolas. Category: Beaches." },
  { id: "boca-grandi", text: "Boca Grandi. Wild and windswept on the southeast coast — powerful surf and steady cross-shore wind make this a kitesurf and bodyboard beach, not a swimming one. Come for the drama, not the dip. \"Not for swimming — the current is no joke. But for wind, waves and an empty beach, nowhere beats it.\" — Shendrick Located in Boca Grandi, San Nicolas. Category: Beaches." },
  { id: "arashi-beach", text: "Arashi Beach. The last beach before the island's northwest tip — calm, shallow and sandy, with a reef close enough to swim to. Palapas, a snack bar, and none of the high-rise crowd.  Located in Arashi, Noord. Category: Beaches." },
  { id: "palm-beach-strip", text: "Palm Beach. The wide, hotel-lined stretch north of Eagle — flat water, watersports desks, and the pier bars. Busiest beach on the island, and the easiest one to spend a whole afternoon on.  Located in Palm Beach, Noord. Category: Beaches." },
  { id: "boca-catalina-shore", text: "Boca Catalina Shore Snorkel. A small rocky cove between Malmok and Arashi where the catamarans anchor offshore. Walk in from the road, swim out twenty metres, and the fish are already there — no boat needed.  Located in Boca Catalina, Malmok. Category: Beaches." },
  { id: "alto-vista-chapel", text: "Alto Vista Chapel & Hilltop Walk. Aruba's first chapel, alone on a hill above the north coast, reached by a lane lined with white crosses. Short walk, big view, and it empties out completely in the late afternoon.  Located in Alto Vista, Noord. Category: Activities." },
  { id: "california-dunes-sunset", text: "California Dunes at Sunset. Rolling white sand dunes behind the lighthouse, walkable in an hour. Go late: the low sun throws the ridges into relief and the whole northwest coast is below you.  Located in Hudishibana, Noord. Category: Activities." },
  { id: "bushiribana-loop", text: "Bushiribana Ruins Coastal Loop. The shell of a 19th-century gold smelter on the windward coast, with a rough loop along the cliffs from Calbas. Exposed, windy, and the sea here does not stop.  Located in Bushiribana, north coast. Category: Activities." },
  { id: "san-nicolas-murals", text: "San Nicolas Mural Walk. The old refinery town turned open-air gallery — dozens of large-scale murals across a few walkable blocks, plus Aruba's oldest bars. Self-guided, or join a walking tour.  Located in San Nicolas. Category: Tours." },
];
